[package]
name = "rcut"
version = "0.0.1"
authors = ["Viet Le <vietlq85@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "2.33"
regex = "1.3"
